version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ai_based_toc_builder:${APP_VERSION:-latest}
    container_name: ai_based_toc_builder
    restart: unless-stopped
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=gpt-4.1-mini
      - PDF_MAX_PAGES=10
      - DEFAULT_THREAD_COUNT=4
      - LOG_LEVEL=warning
    volumes:
      # Mount code for development live reload
      - ./app:/app/app:ro
      # Mount PDF files for processing
      - ./pdf_files:/app/pdf_files:ro
      # Mount prompt.json for dynamic prompt updates
      - ./prompt.json:/app/prompt.json
    ports:
      - "${PORT:-8000}:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/toc/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
