name: Release to PyPI

on:
  release:
    types: [created]

jobs:
  build-and-publish:
    name: Build and Publish Python Package
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history and tags for versioning
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine build
      
      - name: Build package distributions
        run: |
          python -m build --sdist --wheel
      
      - name: Upload distributions to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/*
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
      - name: Log completion message
        run: |
          echo "Release ${{ github.ref_name }} assets created successfully"
          echo "Note: PyPI publishing has been disabled"
